name: portfolio
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  get: ^4.7.2
  flutter_svg: ^2.2.0
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/svg/
    - assets/image/

  fonts:
    - family: KhmerFont
      fonts:
        - asset: assets/font/Khmer CN Kam Rieng V2.ttf
    - family: EnglishFont
      fonts:
        - asset: assets/font/FiraCode-Regular.ttf
    - family: KhmerFontDesc
      fonts:
        - asset: assets/font/Khmvanara.ttf
